In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory



In [4]:
data = pd.read_csv("/content/stock.csv")

In [5]:
data

Stock Index  10-Aug  11-Aug   12-Aug    13-Aug    14-Aug    15-Aug
0         AC3235    0.80   0.660  0.77240  0.983224  0.901211  0.898368
1         AC3236    0.86   0.732  0.85448  1.086645  1.017042  1.029258
2         AC3237    0.93   0.816  0.95024  1.207302       NaN  1.181962
3         AC3238    1.09   1.008  1.16912  1.483091  1.461062  1.531000
4         AC3239     NaN   1.104  1.27856  1.620986  1.615504  1.705519
...          ...     ...     ...      ...       ...       ...       ...
3326      AD2734    0.86   0.732  0.85448  1.086645  1.017042  1.029258
3327      AD2735    0.64   0.468  0.55352  0.707435  0.592327  0.549330
3328      AD2736    0.67   0.504  0.59456  0.759146  0.650243  0.614775
3329      AD2737    0.79   0.648  0.75872  0.965987  0.881906  0.876553
3330      AD2738    0.74   0.588  0.69032  0.879803  0.785380  0.767479

[3331 rows x 7 columns]

In [6]:
data.isnull().any()

Stock Index    False
10-Aug          True
11-Aug          True
12-Aug          True
13-Aug          True
14-Aug          True
15-Aug          True
dtype: bool

In [8]:
data.columns

Index(['Stock Index', '10-Aug', '11-Aug', '12-Aug', '13-Aug', '14-Aug',
       '15-Aug'],
      dtype='object')

In [9]:
data['10-Aug']=data['10-Aug'].fillna(value=data['10-Aug'].mean())

In [10]:
data['11-Aug']=data['11-Aug'].fillna(value=data['11-Aug'].mean())

In [11]:
data['12-Aug']=data['12-Aug'].fillna(value=data['12-Aug'].mean())

In [12]:
data['13-Aug']=data['13-Aug'].fillna(value=data['13-Aug'].mean())

In [13]:
data['14-Aug']=data['14-Aug'].fillna(value=data['14-Aug'].mean())

In [14]:
data['15-Aug']=data['15-Aug'].fillna(value=data['15-Aug'].mean())

In [15]:
data.isnull().any()

Stock Index    False
10-Aug         False
11-Aug         False
12-Aug         False
13-Aug         False
14-Aug         False
15-Aug         False
dtype: bool

In [17]:
trainset = data.iloc[:,1:6].values

In [22]:
testset = data.iloc[:, 2:7].values

In [29]:
testset

array([[0.66      , 0.7724    , 0.983224  , 0.90121088, 0.89836829],
       [0.732     , 0.85448   , 1.0866448 , 1.01704218, 1.02925766],
       [0.816     , 0.95024   , 1.2073024 , 1.16525429, 1.18196192],
       ...,
       [0.504     , 0.59456   , 0.7591456 , 0.65024307, 0.61477467],
       [0.648     , 0.75872   , 0.9659872 , 0.88190566, 0.8765534 ],
       [0.588     , 0.69032   , 0.8798032 , 0.78537958, 0.76747893]])

In [30]:
trainset

array([[0.8       , 0.66      , 0.7724    , 0.983224  , 0.90121088],
       [0.86      , 0.732     , 0.85448   , 1.0866448 , 1.01704218],
       [0.93      , 0.816     , 0.95024   , 1.2073024 , 1.16525429],
       ...,
       [0.67      , 0.504     , 0.59456   , 0.7591456 , 0.65024307],
       [0.79      , 0.648     , 0.75872   , 0.9659872 , 0.88190566],
       [0.74      , 0.588     , 0.69032   , 0.8798032 , 0.78537958]])

In [31]:
trainset.shape

(3331, 5)

In [32]:
testset.shape

(3331, 5)

In [44]:
x_train = []
y_train = []

In [45]:
x_train=trainset

In [46]:
x_train

array([[0.8       , 0.66      , 0.7724    , 0.983224  , 0.90121088],
       [0.86      , 0.732     , 0.85448   , 1.0866448 , 1.01704218],
       [0.93      , 0.816     , 0.95024   , 1.2073024 , 1.16525429],
       ...,
       [0.67      , 0.504     , 0.59456   , 0.7591456 , 0.65024307],
       [0.79      , 0.648     , 0.75872   , 0.9659872 , 0.88190566],
       [0.74      , 0.588     , 0.69032   , 0.8798032 , 0.78537958]])

In [47]:
x_train.shape

(3331, 5)

In [48]:

y_train=data.iloc[:,6].values

In [49]:
y_train

array([0.89836829, 1.02925766, 1.18196192, ..., 0.61477467, 0.8765534 ,
       0.76747893])

In [50]:
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))

In [51]:
x_train.shape[0]

3331

In [52]:
x_train.shape[1]

5

In [62]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [63]:
regressor = Sequential()
regressor.add(LSTM(units = 50,return_sequences = True,input_shape = (x_train.shape[1],1)))

In [64]:
regressor.add(Dropout(0.3))

In [65]:
regressor.add(LSTM(units = 50,return_sequences = True))
regressor.add(Dropout(0.3))

In [66]:
regressor.add(LSTM(units = 50,return_sequences = True))
regressor.add(Dropout(0.3))

In [67]:
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

In [68]:
regressor.add(Dense(units = 1))

In [69]:

regressor.compile(optimizer = 'adam',loss = 'mean_squared_error')

In [70]:
regressor.fit(x_train,y_train,epochs = 100, batch_size = 32)

Epoch 1/100
105/105 [==============================] - 9s 14ms/step - loss: 0.6384
Epoch 2/100
105/105 [==============================] - 1s 14ms/step - loss: 0.0431
Epoch 3/100
105/105 [==============================] - 2s 14ms/step - loss: 0.0361
Epoch 4/100
105/105 [==============================] - 1s 14ms/step - loss: 0.0285
Epoch 5/100
105/105 [==============================] - 2s 14ms/step - loss: 0.0241
Epoch 6/100
105/105 [==============================] - 1s 14ms/step - loss: 0.0245
Epoch 7/100
105/105 [==============================] - 2s 14ms/step - loss: 0.0208
Epoch 8/100
105/105 [==============================] - 1s 14ms/step - loss: 0.0217
Epoch 9/100
105/105 [==============================] - 1s 14ms/step - loss: 0.0277
Epoch 10/100
105/105 [==============================] - 2s 15ms/step - loss: 0.0209
Epoch 11/100
105/105 [==============================] - 2s 14ms/step - loss: 0.0211
Epoch 12/100
105/105 [==============================] - 2s 14ms/step - loss: 0.0199
E

In [71]:
x_test=testset

In [72]:
x_test = np.reshape(x_test, (x_test.shape[0],x_test.shape[1],1))
x_test.shape

(3331, 5, 1)

In [73]:
predicted_price = regressor.predict(x_test)

In [75]:
predicted_price #on16aug

array([[0.88030165],
       [1.0304058 ],
       [1.2077489 ],
       ...,
       [0.5586066 ],
       [0.8553411 ],
       [0.7309586 ]], dtype=float32)

In [85]:
predicted_price.shape

(3331, 1)

In [86]:
f= open("/content/submission.txt","w+")

In [87]:
for i in range(len(predicted_price)):
  string=str(predicted_price[i])
  f.write((string))